  deploy_source: local
  local_file_project: "{{ playbook_dir }}/../../../chat-messenger/docker-compose.prod.yml"
  local_secrets: "{{ playbook_dir }}/../../../chat-messenger/.env.example"
  path_project: /opt/chat-messenger/